# Generated by Django 2.2.2 on 2019-07-31 16:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido_Estatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contenido', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
    ]
