# Generated by Django 2.2.2 on 2019-07-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programa_estudio', '0001_initial'),
        ('seccion', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.administrador')),
                ('seccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seccion.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicacion.publicacion')),
                ('descripcion', models.TextField()),
                ('cuerpo', models.TextField()),
            ],
            bases=('publicacion.publicacion',),
        ),
        migrations.CreateModel(
            name='calendario_prueba',
            fields=[
                ('publicacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='publicacion.publicacion')),
                ('fecha_prueba', models.DateField()),
                ('horario', models.CharField(max_length=10)),
                ('tipocalendario', models.CharField(max_length=10)),
                ('sala', models.CharField(max_length=10)),
                ('asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa_estudio.programa_estudio')),
            ],
            bases=('publicacion.publicacion',),
        ),
    ]
