# Generated by Django 2.2.2 on 2019-07-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='calsemestre',
            field=models.IntegerField(choices=[(1, 'Primer semestre '), (2, 'Segundo semestre')], default=1),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.IntegerField(default=0, verbose_name=[(1, 'Activo (La notica sera publicada)'), (0, 'No Activo(La noticia no estara publicada)')]),
        ),
    ]
