# Generated by Django 2.2.2 on 2019-07-18 21:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
