# Generated by Django 2.2.2 on 2019-07-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0002_auto_20190725_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='semestre',
            field=models.IntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], default='1'),
        ),
    ]
