# Generated by Django 2.2.2 on 2019-07-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0003_auto_20190727_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='calagno',
            field=models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019),
        ),
    ]
