# Generated by Django 2.2.2 on 2019-07-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_auto_20190709_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccion.seccion'),
        ),
    ]
