# Generated by Django 2.2.2 on 2019-07-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_publicacion_calagno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo (La notica sera publicada)'), (0, 'No Activo(La noticia no estara publicada)')], default=0),
        ),
    ]
