# Generated by Django 2.2.2 on 2019-07-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_auto_20190709_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='admin',
        ),
        migrations.DeleteModel(
            name='calendario_prueba',
        ),
    ]
