# Generated by Django 2.2.2 on 2019-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0009_publicacion_pruebas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='pruebas',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='calendarioprueba',
            field=models.IntegerField(choices=[(1, 'Si'), (0, 'No')], default=0),
        ),
    ]
