# Generated by Django 2.2.2 on 2019-07-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_estudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa_estudio',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programa_estudio',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
