# Generated by Django 2.2.2 on 2019-07-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa_estudio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa_estudio',
            name='año',
        ),
        migrations.AddField(
            model_name='programa_estudio',
            name='anno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programa_estudio',
            name='semestre',
            field=models.IntegerField(),
        ),
    ]
