# Generated by Django 2.2.2 on 2019-07-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa_estudio', '0002_auto_20190717_0255'),
        ('programa_estudio', '0002_auto_20190716_0409'),
    ]

    operations = [
    ]
