# Generated by Django 2.2.3 on 2019-07-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('codasig', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('areacon', models.CharField(max_length=30)),
                ('horatel', models.CharField(max_length=15)),
                ('sct', models.IntegerField()),
                ('requisito', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='programa_estudio',
            fields=[
                ('codigo', models.CharField(default='0', max_length=5, primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('asig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asignatura.asignatura')),
            ],
        ),
    ]
