# Generated by Django 2.2.2 on 2019-07-20 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programa_estudio',
            fields=[
                ('codigo', models.CharField(default='0', max_length=5, primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('codasig', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('areacon', models.CharField(max_length=30)),
                ('horatel', models.CharField(max_length=15)),
                ('sct', models.IntegerField()),
                ('requisito', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10')], default=1)),
                ('semestre', models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre')], default='1', max_length=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignatura.programa_estudio')),
            ],
        ),
    ]
