# Generated by Django 2.2.2 on 2019-07-03 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('codasig', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('areacon', models.CharField(max_length=30)),
                ('horatel', models.CharField(max_length=15)),
                ('sct', models.IntegerField()),
                ('requisito', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.administrador')),
            ],
        ),
    ]
