# Generated by Django 2.2.2 on 2019-08-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='areacon',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='requisito',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='requisito',
            field=models.ManyToManyField(blank=True, default=None, to='asignatura.asignatura'),
        ),
    ]
