# Generated by Django 2.2.2 on 2019-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='asig',
            field=models.ManyToManyField(null=True, related_name='_asignatura_asig_+', to='asignatura.asignatura'),
        ),
    ]
