# Generated by Django 2.2.2 on 2019-07-18 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0002_remove_asignatura_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='programa_estudio',
            fields=[
                ('codigo', models.CharField(default='0', max_length=5, primary_key=True, serialize=False)),
                ('año', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('asig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asignatura.asignatura')),
            ],
        ),
    ]
