# Generated by Django 2.2.2 on 2019-07-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0002_asignatura_asig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='asig',
            field=models.ManyToManyField(related_name='_asignatura_asig_+', to='asignatura.asignatura'),
        ),
    ]
