# Generated by Django 2.2.2 on 2019-08-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0002_auto_20190807_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='area_conocimiento',
            field=models.CharField(choices=[('CB', 'Ciencias Básicas'), ('HL', 'Habilidades Laborales'), ('CS', 'Ciencia de la Computación'), ('TI', 'Tecnología de la información'), ('CSOTI', 'Ciencia de la Computación ó Tecnología de la información'), ('FG', 'Formacón general')], default='CS', max_length=10),
        ),
    ]
