# Generated by Django 2.2.2 on 2019-07-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0003_auto_20190725_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='asig',
        ),
    ]
