# Generated by Django 2.2.2 on 2019-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0003_asignatura_area_conocimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='pdf',
            field=models.FileField(blank=True, default=None, upload_to='pdf'),
        ),
    ]
