# Generated by Django 2.2.2 on 2019-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0004_remove_asignatura_asig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='requisito',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='requisito',
            field=models.ManyToManyField(related_name='_asignatura_requisito_+', to='asignatura.asignatura'),
        ),
    ]
