# Generated by Django 2.2.2 on 2019-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignatura', '0005_auto_20190725_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='requisito',
            field=models.ManyToManyField(blank=True, related_name='_asignatura_requisito_+', to='asignatura.asignatura'),
        ),
    ]
